alter table users
  add column system_user_id varchar(100)
  not null;

create table password_tokens (
   id bigint GENERATED BY DEFAULT AS IDENTITY,
   password_token varchar(200) not null,
   expiration_time timestamp not null,
   user_id bigint not null
);

alter table password_tokens
  add constraint pk_password_tokens
  primary key (id);

alter table password_tokens
  add constraint fk_tokens_user
  foreign key (user_id)
  references users(id);